### ISSUE TITLE
does it blur base64 img from api calls?

### ISSUE THREAD

**Issue by sdwcn** [aria1th/sd-webui-nsfw-filter#1]

**Comment by aria1th** [comment]
@sdwcn Yes, it blurrs images from API calls too. 
Here is code snippet and result:

![image](https://github.com/aria1th/sd-webui-nsfw-filter/assets/35677394/a82ea4a2-6fed-4cd3-aa54-4cc402848945)

Remember that this may not work sometimes for certain types of models **(especially 2d!!!)**

it had 15% failure rate for certain models as shown below, so you may need some additional protection for that.

![image](https://github.com/aria1th/sd-webui-nsfw-filter/assets/35677394/b1caec62-97b9-4800-9748-f7a407fa3d3f)

**Comment by sdwcn** [comment]
cool, thx will have a try later
